### ISSUE TITLE
Unstable changes

### ISSUE THREAD

**Issue by wduckitt** [React-Automation-Studio/React-Automation-Studio#80] opened 2022-07-27 07:40 UTC
Hi All,

I  have reviewed all the changes by @giosava94 that were merged in #61 by @hanak , and it has created serious instabillities.

Symptoms:
1. pvserver randomily hangs up
2. if you refresh the browser several times, pvs lose connection, never reconnect.

I realise I was off the project for sometime but release 3.1.0 was very stable, you could leave it for weeks and come back to the same screen. Even the prepared 3.2.0RC branch was just as stable.

I have tried adhockly looking  at the packages in particular reverting to and older version of PyEpics, but the sysmptoms still persist.

I also tried to add a widget on a different branch to report the server statistics, ie no of pvs, connections, no of listening widgets. This will help debuging in future but all i could identify is that the gloabal list of PV'S never gets an updated connection status, once the connection is reastiblished after all sockets are disconnected.

I suspect somewhere a variable was named incorrectly useing the new naming schemes but I'm affraid in its current state its just to difficult too trace. There have been package dependcy upgrades and too much code reformating to trace and find possibly the one line error or which package update has introduced it. I have spent several nights now trying to get to the bottom but it alludes me.

I like the core concept of what has changed but we can't put out a new release based on it,

@hanak  ,can we please try and revert, and give the developer time to trace and fix the instabilities, independently of the master branch? I can review the pull request to revert.

I propose we continue with the original code  as it has track record for a very long time. In parrallel we update the dependancies, and add the minor bug fix that exists in V3.2.0RC branch. 

When the developer is ready for another review and it is stable then we can move forward and use poetry to manage the Python packages

_Originally posted by @wduckitt in https://github.com/React-Automation-Studio/React-Automation-Studio/issues/61#issuecomment-1196032088_

**Comment by wduckitt** [comment] 2022-07-27 10:22
I went back to the V3.1.0 branch an incrementally changed the package dependancies as defined to in the requirements.txt to that in the poetry pyproject.toml.

AS far as I can tell system is stable until with all updates except pyEpics change from V3.4.3 to V3.5.1

I experience similar problems as reported above if i swtich to the newer pyEpics.

This is my contents of requirements.txt:

Flask==2.1.2
Flask-SocketIO==5.1.2
gevent==21.12.0
gevent-websocket==0.10.1
pyepics==3.4.3
PyJWT==1.7.1
python-dotenv==0.20.0
bcrypt==3.2.2
pymongo==4.1.1
flask-cors==3.0.10
python-ldap==3.4.0
google-api-python-client==2.47.0

**Comment by wduckitt** [comment] 2022-07-27 10:39
Further, I then went back to the master and had a look at the at the poetry dependancies. It appears the cause was PyEpics. 
Similar to an issue i picked in #74.  Although I though I had downgrade it yesterday, it appears not. I feel the way the lock file is used or generated and way the package versions are specified inth toml file create a hidden artifact. 

Perhaps we should drop the lock file and use the toml with exact version to control the dependancy:
I used these contents in the toml, but deleted the lock file, and removed the copy of the lock file in the pvserver docker file.
 
I can produce a stable enviroment with no issues as reported before:

[tool.poetry]
name = "pvserver"
version = "3.2.0-alpha"
description = "RAS Python backend. It mainly manages connections with PVs, through a websocket connection, authentication, authorization, plus other optional functionalities."
authors = ["React Automation Studio Team <rasadmin@tlabs.ac.za>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/React-Automation-Studio/React-Automation-Studio"

[tool.poetry.dependencies]
python = "3.8.7"
Flask = "2.1.2"
pyepics = "3.4.3"
gevent = "21.12.0"
bcrypt = "3.2.2"
python-ldap = "3.4.0"
pymongo = "4.1.1"
python-dotenv = "0.20.0"
Flask-Cors = "3.0.10"
Flask-SocketIO = "5.1.2"
PyJWT = "1.7.1"
google-api-python-client = "2.47.0"
gevent-websocket = "0.10.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

**Comment by wduckitt** [comment] 2022-07-27 10:41
If anyone has any objections i can prepare a pull request, review and then hopefully we can close the issue, and resolve pyEpics depancy at a later stage

**Comment by hanak** [comment] 2022-07-27 10:42
Nice update. It seems that pyepics 3.5.1 is two releases away from pyepics 3.4.3. Diff shows that:
* caget and caput use a connection timeout of 5 seconds in 3.5.1. It used to be 60 seconds be default and it was driven by the argument timeout. pvServer does not seem to use caget/caput.
* memcopy was replaced by deepcopy in element_count(). I was not able to find it in pvServer.
* PV.cainfo prints additional information in 3.5.1. I think cainfo is not used by pvServer.
* PV.disconnect cleans more data from cache in 3.5.1. pvServer uses PV.disconnect() but it drops the pv from clientPVlist right after it. There does not seem to be any protection from concurrency. Yet, I have not evidence this is the cause.

**Comment by hanak** [comment] 2022-07-27 10:45
Regarding the lock file. Poetry documentation recommends including the lock file into the version control (see "Commit your poetry.lock file to version control" in https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control). Yet, removing a copy of the lock file from the docker sounds good.

**Comment by hanak** [comment] 2022-07-27 10:49
Regarding downgrading pyepics to 3.4.3. If we are getting stable behavior with 3.4.3, let us use this version.

**Comment by wduckitt** [comment] 2022-07-27 11:49
I feel if we leave pyEpics at 3.4.3 we can move on, and later create an issue to update pyEpics, and the epics base used in the pvServer concurrently.

**Comment by hanak** [comment] 2022-07-28 06:40
I think I agree. I have added a comment to #42 which should upgrade dependencies so that we keep that on mind while resolving #42.

**Closed** 2022-07-28 09:54 UTC
